# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='name',
            new_name='title',
        ),
    ]
